spring.application.name=orderitemscontroller


spring.datasource.url=jdbc:postgresql://localhost:5432/orderitemsdb
spring.datasource.username=postgres
spring.datasource.password=manojkasu
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8085

jwt.secret=+PS4A0uVWIDBqub+3SRCHcy+HqW0NjLPF7q2Wwlm/BE=