spring.application.name=productController

server.port=8082
spring.datasource.url = jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=manojkasu
spring.datasource.database-platform=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=+PS4A0uVWIDBqub+3SRCHcy+HqW0NjLPF7q2Wwlm/BE=